### ISSUE TITLE
代码块可以插入，但是高亮evernote不支持

### ISSUE THREAD

**Issue by doctor-fun** [tansongchen/AnkiEvernoteImporter#3]
只能通过简书编辑好代码，发布后整体复制到evernote，再从evernote导入到anki，实在是太麻烦了

**Comment by tansongchen** [comment]
Evernote 普通笔记的代码块功能不是很好用。但是，Evernote 的 Markdown 笔记插入代码块时自动高亮，并且本插件在处理 Markdown 笔记时调用 Pygments 库来高亮，最终在 Anki 里的效果如下图。欢迎试用！

![image](https://user-images.githubusercontent.com/31927845/70301312-e01d8200-17ae-11ea-976b-209b68016885.png)

**Comment by doctor-fun** [comment]
got it

**Comment by doctor-fun** [comment]
明白谢谢老哥

在 2019-12-06 14:31:41，"谭淞宸" <notifications@github.com> 写道：


Evernote 普通笔记的代码块功能不是很好用。但是，Evernote 的 Markdown 笔记插入代码块时自动高亮，并且本插件在处理 Markdown 笔记时调用 Pygments 库来高亮，最终在 Anki 里的效果如下图。欢迎试用！

**Comment by doctor-fun** [comment]
老哥试了下，导入时会出错，抱歉，可以举个例子么



找出数组中连续的乘积小于目标值的子序列(-->这个是h2标题)
```java
import java.util.*;
class SubarrayProductLessThanK {
  public static List<List<Integer>> findSubarrays(int[] arr, int target) {
    List<List<Integer>> result = new ArrayList<>();
    int product = 1, left = 0;
    for (int right = 0; right < arr.length; right++) {
      product *= arr[right];
      while (product >= target && left < arr.length)
        product /= arr[left++];
      // since the product of all numbers from left to right is less than the target therefore,
      // all subarrays from lef to right will have a product less than the target too; to avoid
      // duplicates, we will start with a subarray containing only arr[right] and then extend it
      List<Integer> tempList = new LinkedList<>();
      for (int i = right; i >= left; i--) {
        tempList.add(0, arr[i]);
        result.add(new ArrayList<>(tempList));
      }
    }
    return result;
  }

  public static void main(String[] args) {
    System.out.println(SubarrayProductLessThanK.findSubarrays(new int[] { 2, 5, 3, 10 }, 30));
    System.out.println(SubarrayProductLessThanK.findSubarrays(new int[] { 8, 2, 6, 5 }, 50));
  }
}
```

**Comment by tansongchen** [comment]
我看了一下，似乎问题出在 Anki 自己身上，我在 Anki 外部测试可以成功地做高亮（如果你会 Python 的话可以克隆一份源码用 test.py 做测试），这个问题在未来的 2.1.16 版本会解决。

如果你急用，我可以做一个命令行版本的工具，从 Markdown 生成 txt 格式的导入文件。

**Comment by doctor-fun** [comment]
麻烦老哥做个命令行版本。。。因为markdown还是用的多，给老哥点赞了

**Comment by tansongchen** [comment]
不好意思，最近正在期末考试，刚写了一个命令行版的，在插件文件夹下运行

```bash
python3 convert.py xxx.md
```

即可在当前文件下生成 `import.txt`。不过现在好像 Anki 的服务器在抽风，我上传不上去……明天再试试

**Comment by doctor-fun** [comment]
非常感谢




| |
方晨
|
|
邮箱：fxf432@163.com
|

签名由 网易邮箱大师 定制

在2019年12月31日 06:40，谭淞宸 写道：

不好意思，最近正在期末考试，刚写了一个命令行版的，在插件文件夹下运行

python3 convert.py xxx.md

即可在当前文件下生成 import.txt。不过现在好像 Anki 的服务器在抽风，我上传不上去……明天再试试

**Comment by tansongchen** [comment]
刚刚上传上去了，你在这里点击 View Files，然后在那个目录下运行就可以了。

![image](https://user-images.githubusercontent.com/31927845/71643373-e3dfee00-2cf3-11ea-9cf9-5afbf9a2b70f.png)

**Comment by tansongchen** [comment]
我意识到之前 Anki 的问题已经解决了，所以最近我会在 GUI 界面版本的程序中处理好代码高亮，以后就不再提供命令行版本了。

**Comment by tansongchen** [comment]
v1.0.0-beta 公测版已经解决此问题。你可以现在在 Releases 下载或者在插件官网下载，也可以再等几天到 v1.0.0 正式版。
