### ISSUE TITLE
window版本存在下列问题，望解决

### ISSUE THREAD

**Issue by springrain1** [tansongchen/AnkiEvernoteImporter#5]
1. 对于多张卡片，Evernote自带的有序及无序列表导入会导致合并为1张卡片；
2. 对于插入图片的Q&A卡片，windows版本不能显示
![image](https://user-images.githubusercontent.com/51806784/71606586-0f0bf580-2bad-11ea-9e0a-66e12fd5441f.png)
![image](https://user-images.githubusercontent.com/51806784/71606600-2519b600-2bad-11ea-9019-90535030b5af.png)

**Comment by springrain1** [comment]
`<div><div>Q：Question 1&nbsp;xxx</div><div>A：</div><div style="text-align: left;"><img data-filename="Image.png" src="YinXiangBiJi.enex_files/Image.png" type="image/png" width="347"></div><div style="text-align: left;"><br></div><div style="text-align: left;">Q：Question 2&nbsp;xxx</div><div style="text-align: left;">A：</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div>代码</div></div><div style="text-align: left;">1. 有序</div><div style="text-align: left;">- 无序任务</div><ul><li><div style="text-align: left;">无序1</div></li></ul><ol><li><div style="text-align: left;">有序1</div></li></ol><div><br></div></div>`

**Comment by tansongchen** [comment]
好的，能将导出的 HTML 源文件发来看一下吗？

**Comment by springrain1** [comment]
> 好的，能将导出的 HTML 源文件发来看一下吗？


[印象笔记Q&A测试.zip](https://github.com/tansongchen/Evernote2Anki/files/4014944/Q.A.zip)

**Comment by tansongchen** [comment]
插入的图片在 macOS 上能显示。我手头没有 Windows，只能推测，原因可能是：

Anki 要求所有媒体文件不能存放在子目录中，而印象笔记导出的时候 `<img src="">` 属性是含有一层文件夹的，也就是 `xxx_files/`，我需要把它替换成文件本身的 baseName。

Windows 上用 `os.path.join` 方法返回的路径是 `\` 分隔的，而 HTML 中仍然是 `/`，所以可能没有成功发生替换。为此，可不可以麻烦你帮我做个测试，定位到插件文件夹的 `__init__.py` 第 41 行，把

```python
mediaRelativePath = os.path.join(os.path.basename(mediaDir), media)
```

换成

```python
mediaRelativePath = '%s/%s' % (os.path.basename(mediaDir), media)
```

如果这样可以解决的话就添加到下次更新中。

**Comment by springrain1** [comment]
没问题------------------ 原始邮件 ------------------
发件人: "谭淞宸"<notifications@github.com>
发送时间: 2020年1月3日(星期五) 上午9:03
收件人: "tansongchen/Evernote2Anki"<Evernote2Anki@noreply.github.com>;
抄送: "springrain1"<1789572223@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tansongchen/Evernote2Anki] window版本存在下列问题，望解决 (#5)



插入的图片在 macOS 上能显示。我手头没有 Windows，只能推测，原因可能是：
 
Anki 要求所有媒体文&#x4EF6;不能存放在子目录中，而印象笔记导出的时候 <img src=""> 属性是含有一层文&#x4EF6;夹的，也就是 xxx_files/，我需要把它替换成文&#x4EF6;本身的 baseName。
 
Windows 上用 os.path.join 方法返回的路径是 \ 分隔的，而 HTML 中仍然是 /，所以可能没有成功发生替换。为此，可不可以麻烦你帮我做个测试，定位到插&#x4EF6;文&#x4EF6;夹的 __init__.py 第 41 行，把
 mediaRelativePath = os.path.join(os.path.basename(mediaDir), media)
 
换成
 mediaRelativePath = '%s/%s' % (os.path.basename(mediaDir), media)
 
如果这样可以解决的话就添加到下次更新中。
 
&mdash;

**Comment by tansongchen** [comment]
至于多张卡片合并为一张的问题，我上一次拿到 Windows 的模板文件的时候它的页面容器还是 `body > div > span`，这次你发来的是 `body > div > span > div`，导致程序把最后那个 `div` 整个误判为一组 QA……我再问问其他人，如果是版本不同导致的话，我把写法改一下，改成搜索第一个 QA 并根据它所在的层级确定合理的层级。

**Comment by springrain1** [comment]
> 至于多张卡片合并为一张的问题，我上一次拿到 Windows 的模板文件的时候它的页面容器还是 `body > div > span`，这次你发来的是 `body > div > span > div`，导致程序把最后那个 `div` 整个误判为一组 QA……我再问问其他人，如果是版本不同导致的话，我把写法改一下，改成搜索第一个 QA 并根据它所在的层级确定合理的层级。

好的，感谢！

**Comment by springrain1** [comment]
> 没问题------------------ 原始邮件 ------------------ 发件人: "谭淞宸"<notifications@github.com> 发送时间: 2020年1月3日(星期五) 上午9:03 收件人: "tansongchen/Evernote2Anki"<Evernote2Anki@noreply.github.com>; 抄送: "springrain1"<1789572223@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [tansongchen/Evernote2Anki] window版本存在下列问题，望解决 (#5) 插入的图片在 macOS 上能显示。我手头没有 Windows，只能推测，原因可能是： Anki 要求所有媒体文&#x4EF6;不能存放在子目录中，而印象笔记导出的时候 <img src=""> 属性是含有一层文&#x4EF6;夹的，也就是 xxx_files/，我需要把它替换成文&#x4EF6;本身的 baseName。 Windows 上用 os.path.join 方法返回的路径是 \ 分隔的，而 HTML 中仍然是 /，所以可能没有成功发生替换。为此，可不可以麻烦你帮我做个测试，定位到插&#x4EF6;文&#x4EF6;夹的 __init__.py 第 41 行，把 mediaRelativePath = os.path.join(os.path.basename(mediaDir), media) 换成 mediaRelativePath = '%s/%s' % (os.path.basename(mediaDir), media) 如果这样可以解决的话就添加到下次更新中。 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
![image](https://user-images.githubusercontent.com/51806784/71702316-abcacf00-2e09-11ea-9923-b8f9438d2cbe.png)


![image](https://user-images.githubusercontent.com/51806784/71702314-a5d4ee00-2e09-11ea-966b-fc6ef699f518.png)
这样就可以了，非常感谢您！
